import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavigationBar from '../components/Navbar/Navigationbar'
import Footer from '../components/Footer/footer'
import Banner from '../components/Banner/Banner'


export default function Home() {
  return (
    <div>
      <Head>
        <title>SparkLaunch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>
      <NavigationBar/>

      <main className=' h-[50rem]'>
        <Banner/>
      </main>

      <footer className="">
      {/* <Footer/> */}
      
      </footer>
    </div>
  )
}
