import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NavigationBar from '../components/Navbar/Navigationbar'
import Footer from '../components/Footer/footer'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>SparkLaunch</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>
      <NavigationBar/>

      <main className={styles.main}>
      </main>

      <footer className="">
       <Footer/>
      
      </footer>
    </div>
  )
}
